spring:
  application:
    name: spring-web-future-error

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.example.web: DEBUG
