name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Spotless check
        run: mvn -B -q -DskipTests spotless:check

      - name: Run tests
        run: mvn -B -q test


